### PR TITLE
Add OPTIONS environment variable to allow filters

### PR DESCRIPTION
**Pull request by neredera**

### CODE REVIEW

**Review by jokay — CHANGES_REQUESTED** [review]
Good idea :)

### Issue 1

ENV var `OPTIONS` needs to be added [here](https://github.com/jokay/docker-prune/blob/main/src/Dockerfile#L4) as well.


### Issue 2

And this one needs to be addressed to satisfy the Super-Linter:

```sh
In src/docker-entrypoint.sh line 12:
        docker "${cur}" prune -f ${OPTIONS}
                                 ^--------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
        docker "${cur}" prune -f "${OPTIONS}"
```

**Comment by neredera** [comment]
> ### Issue 2
> And this one needs to be addressed to satisfy the Super-Linter:
> 
> ```shell
> In src/docker-entrypoint.sh line 12:
>         docker "${cur}" prune -f ${OPTIONS}
>                                  ^--------^ SC2086: Double quote to prevent globbing and word splitting.
> 
> Did you mean: 
>         docker "${cur}" prune -f "${OPTIONS}"
> ```

I think in this case it needs to be without quotes (i.e. supress warning), as several options are possible. Or would you prefer a specific option for filtering?

**Comment by jokay** [comment]
`docker volume prune -f` does not support this (or any?) filter:

```sh
docker volume prune -f --filter until=24h
Error response from daemon: Invalid filter 'until'
```

**Comment by jokay** [comment]
> I think in this case it needs to be without quotes (i.e. supress warning), as several options are possible. Or would you prefer a specific option for filtering?

Yes, correct. You may add `# shellcheck disable=SC2086` before this line then.

**Pull request merged**
